### ISSUE TITLE
Can't trigger script with alias name

### ISSUE THREAD

**Issue by nabulke** [danimtb/dasshio#22]
This configuration works:

```
{
  "buttons": [
    {
      "name": "Nerf",
      "address": "AC:XX:XX:XX:XX:XX",
      "domain": "script",
      "service": "12334567890",
      "service_data": "{}"
    }
  ]
}
```
while this doesn't:

```
{
  "buttons": [
    {
      "name": "Nerf",
      "address": "AC:XX:XX:XX:XX:XX",
      "domain": "script",
      "service": "aktiviereradio",
      "service_data": "{}"
    }
  ]
}
```
My script (only the beginning):
```
'12334567890':
  alias: AktiviereRadio
  sequence: 
```
In case it doesn't work, I see the following error in the log:

> WARNING (MainThread) [homeassistant.core] Unable to find service script/aktiviereradio

>  | INFO | Nerf button pressed!
>  | INFO | Request: http://hassio/homeassistant/api/services/script/aktiviereradio
>  | INFO | Status Code: 200
>  | INFO | Successful request
>  | INFO | Packet captured, waiting 20s ..

Using Dashio 0.2.0
Home Assistant Hass.io 0.59.2

Great add-on by the way! Thanks for developing it

**Comment by nabulke** [comment]
I also don't see the service "aktiviereradio" in my services list of the dashboard (even after a restart). Only the "script.12334567890" is listed there.
So it might be a problem with my hass.io installation and not the dasshio?

**Comment by danimtb** [comment]
Home Assistant API knows nothing about you alias. The alias field have effect just in the UI but not in the underlying code, so making a request to `http://hassio/homeassistant/api/services/script/aktiviereradio` should fail.

`domain`, `service`, and `service_data` parameter from Dasshio just mimic the fields of the dev tab. If you don't see your script name "AktiviereRadio" there it is because it is not reachable through the home assistant API and Dasshio will fail to make a request to that service.

Hope this helps!
