### ISSUE TITLE
Some of my buttons no longer being detected

### ISSUE THREAD

**Issue by d0ugal** [danimtb/dasshio#59]
Recently a number of my buttons have stopped working, they still flash etc. and appear to be working. However, I see nothing in the dasshio logs. This is after months of everything working flawlessly.

Is there a good way to debug and investigate this?

**Comment by danimtb** [comment]
One trick to make sure your dash button is actually connecting to your wifi after a button press would be to activate the amazon notifications in the app. Just after the button press you should receive an email from amazon requesting to finish your amazon das configuration.

I had to do this test some weeks ago and found that my dash button was flashing but not connecting to wifi due to low battery. Just opened it up and replaced AAA battery with a fresh one 😄 

Hope it helps

**Comment by d0ugal** [comment]
Oh yeah, I forgot to say, I still get those annoying emails :)

Given that some buttons work, and for the buttons that don't work I still get emails... I guess that means it is something at the network level? Hmm.

Maybe I'll try setting them up again with wifi etc. That might help.

I just thought I'd check here to see if there was something else I might be missing. I guess this can probably be closed. Thanks for your help and for the addon!

**Comment by danimtb** [comment]
I will keep it open some days just in case it is a general problem. In the past I heard that Amazon may be unconfiguring those buttons that didn't complete the setup process (final step of choosing an article) but didn't have the chance to test it.

Please report back if this happens to be a general issue in the end, otherwise I will close the issue. Thanks a lot and glad you find the addon useful! 😃

**Comment by Hassfan** [comment]
Hi,

I have a similar sounding issue. I have two buttons that stopped working a few days ago after I upgraded to 0.79.3 

I still get the amazon emails after the first button press each day and I also get an error in the logs as follows:

2018-10-04 17:48:25,925 | INFO | Starting sniffing...
2018-10-05 18:37:46,124 | INFO | Music button pressed!
2018-10-05 18:37:46,125 | INFO | Request: http://hassio/homeassistant/api/services/switch/toggle
2018-10-05 18:37:46,139 | INFO | Status Code: 401
2018-10-05 18:37:46,139 | ERROR | Bad request

I think a 401 error is due to authentication, but not sure what I need to change to address this.

Thanks and thanks for the amazing add on!

**Comment by d0ugal** [comment]
@Hassfan That is a different issue, but I actually hit something similar in my own addon. I fixed it by adding the manager hassio_role. https://github.com/d0ugal/hassio-dropbox-upload/commit/763e1af11a25343ab3b05dc1dcd565738be0a116

**Comment by d0ugal** [comment]
I managed to do some further testing, I think there is something up with the buttons. Maybe Amazon did de-register them. Setting them up again doesn't seem to be fully working, I don't really understand. However, they did trigger correctly a few times during my attempts at resetting them up! (my lights went on and off). So I think I can confirm the addon it working.

I'll close this, but if I learn anything interesting I'll come and add it here incase somebody else finds this...
