### ISSUE TITLE
Dasshio wifi problem

### ISSUE THREAD

**Issue by dustardly** [danimtb/dasshio#87]
I have dasshio on 2 raspberry 3 b+

First master have a Lan connection and working good with dasshio 0.3.6 and HA 0.91.4

Second(same 0.3.6. dasshio and HA 0.91.4) have a wifi connection to the same lan and never see any button  all the time 
2019-04-18 10:20:34,530 | INFO | Reading config file: /data/options.json
2019-04-18 10:20:34,536 | INFO | Starting...
2019-04-18 10:20:34,537 | INFO | Starting sniffing...
but never see any button, while with 0.3.1 see when it pushed.

It 's a bug on new version ? 

Same config for both dasshio, try different button , nothing change.
try to set timeout more then 20, since to 40 nothing , don't see when they are pushed.

**Comment by ghost** [comment]
I have exactly the same problem dasshio v 0.3.6 and HA v 0.94.1 on a raspi 3B+.
Button presses are not being detected for different timeout settings.
Haven't changed my config in any way before the update from pre 0.90.0 to 0.94.1.
 I assume its a problem related to the new versions of HA since the last update to dasshio is a couple of months old now and HA has introduced some major breaking changes in the meantime.
